version = 0.1
[default.deploy.parameters]
stack_name = "spring-petshop"
resolve_s3 = true
s3_prefix = "spring-petshop"
region = "ap-northeast-1"
profile = "chelky"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
